"""
reporter.py — Generates structured Markdown audit reports for HealX runs.
"""

import os
import re
from datetime import datetime


def generate_report(
    test_name: str,
    triage_results: list[bool],
    verdict: str,
    result: dict,
) -> str:
    """
    Build the full Markdown audit report string and write it to disk.
    Returns the path of the written file.
    """
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"HEALX_REPORT_{ts}.md"
    report_path = os.path.join(os.path.abspath(os.path.dirname(__file__)), filename)

    triage_icons = " ".join("[PASS]" if r else "[FAIL]" for r in triage_results)
    pass_count = sum(triage_results)
    fail_count = len(triage_results) - pass_count

    mode_label = {
        "MODE_A": "Deterministic Bug (Mode A)",
        "MODE_B": "Flaky Test (Mode B)",
        "NO_BUG": "No Bug Detected",
    }.get(verdict, verdict)

    diagnosis_text = result.get("diagnosis", "N/A")
    diff_text = result.get("diff", "")
    stress_passes = result.get("stress_passes", "N/A")
    stress_total = result.get("stress_total", "N/A")
    success = result.get("success", False)

    # Subagent table (Mode B only)
    subagent_section = ""
    if verdict == "MODE_B":
        winner = result.get("winner", "N/A")
        subagent_section = f"""
## Parallel Subagent Hypothesis Matrix

| Subagent    | Hypothesis           | Status                          |
|-------------|----------------------|---------------------------------|
| Timing      | Unmocked sleep/async | {"**WINNER [PASS]**" if winner == "timing" else "TESTED"} |
| State       | Shared state leak    | {"**WINNER [PASS]**" if winner == "state" else "TESTED"} |
| Randomness  | Unseeded RNG         | {"**WINNER [PASS]**" if winner == "randomness" else "TESTED"} |

**Winning Hypothesis:** `{winner}`
"""

    stress_section = ""
    if isinstance(stress_passes, int):
        pct = int(100 * stress_passes / stress_total) if stress_total else 0
        bar_filled = int(pct / 5)
        bar = "█" * bar_filled + "░" * (20 - bar_filled)
        stress_section = f"""
## Stress Verification

| Metric        | Value              |
|---------------|--------------------|
| Runs executed | {stress_total}     |
| Runs passed   | {stress_passes}    |
| Pass rate     | {pct}%             |

```
[{bar}] {stress_passes}/{stress_total} passed
```
"""

    diff_section = ""
    if diff_text.strip():
        diff_section = f"""
## Code Diff Applied

```diff
{diff_text}
```
"""

    triage_row = "| ".join("[PASS]" if r else "[FAIL]" for r in triage_results)

    report = f"""# HealX Audit Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Test Target:** `{test_name}`
**Overall Result:** {"[SUCCESS]" if success else "[FAILED]"}

---

## Triage Summary

| Run | 1 | 2 | 3 | 4 | 5 |
|-----|---|---|---|---|---|
| Result | {triage_row} |

Triage: {triage_icons} -- **{pass_count} passed / {fail_count} failed**

**Classification:** `{mode_label}`

---

## IBM Granite Root-Cause Analysis

> {diagnosis_text}

---
{subagent_section}
{stress_section}
{diff_section}
---

*Report generated by HealX - Autonomous AI Debugger powered by IBM Granite via watsonx.ai*
"""

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report)

    return report_path
